CREATE TABLE weather_readings (
  id SERIAL PRIMARY KEY,
  city VARCHAR(255),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  generationtime_ms DOUBLE PRECISION,
  utc_offset_seconds INTEGER,
  timezone VARCHAR(100),
  timezone_abbreviation VARCHAR(50),
  elevation DOUBLE PRECISION,
  cur_time TIMESTAMP,
  interval_sec INTEGER,
  temperature_2m DOUBLE PRECISION,
  apparent_temperature DOUBLE PRECISION,
  relative_humidity_2m DOUBLE PRECISION,
  is_day INTEGER,
  precipitation DOUBLE PRECISION,
  rain DOUBLE PRECISION,
  showers DOUBLE PRECISION,
  snowfall DOUBLE PRECISION,
  weathercode INTEGER,
  cloud_cover INTEGER,
  pressure_msl DOUBLE PRECISION,
  surface_pressure DOUBLE PRECISION,
  wind_speed_10m DOUBLE PRECISION,
  wind_direction_10m INTEGER,
  wind_gusts_10m DOUBLE PRECISION,
  temperature_unit VARCHAR(20),
  wind_speed_unit VARCHAR(20)
);
