services:
  airflow:
    build: .
    container_name: airflow
    env_file:
      - .env.airflow
    restart: no
    networks:
      - weather-net
    user: "${AIRFLOW_UID:-1000}:0"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_CORE_ENABLE_XCOM_PICKLING: "true"
      _AIRFLOW_DB_MIGRATE: "true"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: standalone
